version: "2.0"
services:
  db:
    image: mongo:4.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo

  api:
    image: shop-api
    ports:
      - "8080:8080"
    environment:
      - MONGO=mongodb://mongo:mongo@db:27017
      - DBNAME=shop
    mem_limit: 150Mb
    memswap_limit: 150Mb
    links:
      - db
    depends_on:
      - db
